### PR TITLE
Added note about Government Cloud

### PR DESCRIPTION
**Pull request by PramodBalusu**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@PramodBalusu : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger12** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger13** [comment]
@KumarVivek : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger14** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger17** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger18** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Review by MSFTMan — APPROVED** [review]

**Pull request merged**
