### PR TITLE
Fixing some spelling errors

### PR DESCRIPTION
**Pull request by modery**
Correcting some spelling of various product names (SharePoint, Teams, others)

### CODE REVIEW

**Comment by PRMerger15** [comment]
@modery : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @Dean-Haas, @nijemcevic

**Comment by PRMerger12** [comment]
@modery : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @MSFTMAN, @vashr, @mariosleon, @Dean-Haas

**Comment by PRMerger7** [comment]
@modery : Thanks for your contribution! The author(s) have been notified to review your proposed change. @Dean-Haas

**Comment by PRMerger15** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @Dean-Haas

**Comment by PRMerger12** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @Dean-Haas

**Review by mariosleon — APPROVED** [review]

**Comment by PRMerger16** [comment]
@mariosleon : Thanks for your contribution! The author(s) have been notified to review your proposed change. @Dean-Haas

**Comment by PRMerger9** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @Dean-Haas

**Comment by PRMerger12** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @Dean-Haas

**Pull request merged**
