### PR TITLE
update monitor.md

### PR DESCRIPTION
**Pull request by lanlanlee2008**
to include PPAC V1 reports and CoE starter kit details
[Not familiar with how to add pictures and format, will send a separate email to Deon.

created ppac
runs ppac
usage ppac

### CODE REVIEW

**Comment by PRMerger17** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger20** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger6** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by MSFTMan** [comment]
closing this pr per conversation with @lanlanlee2008

**Pull request closed without merging**
