### PR TITLE
Adding video - Getting Started

### PR DESCRIPTION
**Pull request by sbasi19**
Added Video in Getting Started Doc

### CODE REVIEW

**Comment by PRMerger7** [comment]
@sbasi19 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger13** [comment]
@sbasi19 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger9** [comment]
@sbasi19 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MSFTMan** [comment]
@sbasi19 I am handling these in the private repo. thanks!

**Pull request closed without merging**
