### PR TITLE
Provide a link to the overview content with more details on how to us…

### PR DESCRIPTION
**Pull request by simonsabin**
…e the actions

This section doesn't provide a link to the overview content with more details on how to use the actions.
The table and list extraction aren't  obvious without referring to the guide.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@simonsabin : Thanks for your contribution! The author(s) have been notified to review your proposed change. @mariosleon

**Comment by PRMerger9** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @mariosleon

**Comment by mariosleon** [comment]
@simonsabin Thank you for your suggestion. We are currently working on this along with other topics and they are planned to be released soon.

**Comment by mariosleon** [comment]
@simonsabin Once again, thank you for your suggestion. The documentation has been updated containing the links from the actions reference to the respective topics and vice-versa.

**Comment by simonsabin** [comment]
Do you have a PR or commit with the changes?

**Comment by mariosleon** [comment]
@simonsabin Please find the commit in the following link https://github.com/MicrosoftDocs/power-automate-docs/commit/089854439eecced743c3cb7a92ff9d84605bbbfb

**Pull request closed without merging**
