### PR TITLE
Correcting a few broken links

### PR DESCRIPTION
**Pull request by modery**
Correcting a few broken links across a few pages

### CODE REVIEW

**Comment by PRMerger3** [comment]
@modery : Thanks for your contribution! The author(s) have been notified to review your proposed change. @MSFTMAN, @MSFTMan, @msftman, @masisley

**Comment by PRMerger17** [comment]
@modery : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by MSFTMan — APPROVED** [review]

**Comment by PRMerger16** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
