### PR TITLE
Repo sync working branch

### PR DESCRIPTION
**Pull request by dattatray-patil**
get-started-logic-flow.md changes
1. Added "flow" to "New flow" 
2. Replaced "Automated-from blank" to "Automated cloud flow".
3. Added new image for "Automated cloud flow"
4. Replaced/Reworded few text add new Images "Create flow option"
5. Added new image for twitter sign in option. add note for allowing permission to App
6. Correct bullet number.
7. Reformmated Step 7 image for #azure
8. Updated dynamic value screen shot.
9. replaced token field screen shot.
create-flow
add-parameter
build-your-automated-cloud-flow
message-token
name-search-trigger
sign-in-to-twitter
twitter-keyword
[get-started-logic-flo.txt](https://github.com/MicrosoftDocs/power-automate-docs/files/5937713/get-started-logic-flo.txt)

run-scheduled-tasks.md changes
Replaced Scheduled - "from cloud" to "Cloud"
1. Added "flow" word in Select **New flow** and then 
2.. Replaced from cloud to **Scheduled cloud flow**.

Media update for cloud image (create-flow).

### CODE REVIEW

**Comment by PRMerger14** [comment]
@dattatray-patil : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger17** [comment]
@dattatray-patil : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger18** [comment]
@dattatray-patil : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger18** [comment]
@dattatray-patil : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger19** [comment]
@dattatray-patil : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger7** [comment]
@dattatray-patil : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger8** [comment]
@dattatray-patil : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger8** [comment]
@dattatray-patil : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger9** [comment]
@dattatray-patil : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by dattatray-patil** [comment]
Dear All,
I am new to github, I am still working on some of the other content which are depreciated or updated. Please keep this request open or guide me. Thank you!

**Comment by dattatray-patil** [comment]
Thank you all, I will work offline.will create new pull request once it’s content is ready. Thank you once again.

**Comment by dattatray-patil** [comment]
Dear all,

I stopped working on this pull request. please review my changes and kindly provide us valuable feedback, Thank you!

**Comment by dattatray-patil** [comment]
@MSFTMan  Could you review and let us know your inputs. thank you!
@PRMerger7, @PRMerger8,  @PRMerger9, @PRMerger14, @PRMerger17, @PRMerger18 and @PRMerger19 thank you!

**Review by Josegto1 — APPROVED** [review]

**Comment by Josegto1** [comment]
> @MSFTMan Could you review and let us know your inputs. thank you!
> @PRMerger7, @PRMerger8, @PRMerger9, @PRMerger14, @PRMerger17, @PRMerger18 and @PRMerger19 thank you!

Done

**Review by Josegto1 — APPROVED** [review]

**Pull request closed without merging**
