### PR TITLE
Removing ADAL

### PR DESCRIPTION
**Pull request by rwike77**
ADAL is actually a client library and is being deprecated:  https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration

### CODE REVIEW

**Comment by PRMerger6** [comment]
@rwike77 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@rwike77 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rwike77** [comment]
@masisley, when you get a moment can you take a look at this?  Thanks.

**Comment by PRMerger7** [comment]
@KumarVivek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
