### PR TITLE
Update us-govt.md

### PR DESCRIPTION
**Pull request by junterpfe**
adding required urls for the PowerAutomate API.

### CODE REVIEW

**Comment by junterpfe** [comment]
IRS was asking for it.
They didn't want to blanket allow microsoft.us and micrsoft.com
Perhaps flow.microsoft.us?

John Unterseher MCSE MCSA MCT
Microsoft CSA
813.260.0162

If you have any feedback about my work, please let me or my manager Chris Sloyan ***@***.******@***.***> know or fill out the following form Feedback<http://aka.ms/junterfeedback>

**Comment by junterpfe** [comment]
They have allowed things like powerplatform.microsoft.us because it was explicitly called out in the box above that.

John Unterseher MCSE MCSA MCT
Microsoft CSA
813.260.0162

If you have any feedback about my work, please let me or my manager Chris Sloyan ***@***.******@***.***> know or fill out the following form Feedback<http://aka.ms/junterfeedback>

**Comment by junterpfe** [comment]
They really want a full list of all the endpoints and what they do but I'm trying to at least get them unblocked right now.

John Unterseher MCSE MCSA MCT
Microsoft CSA
813.260.0162

If you have any feedback about my work, please let me or my manager Chris Sloyan ***@***.******@***.***> know or fill out the following form Feedback<http://aka.ms/junterfeedback>

**Comment by kenseongtan** [comment]
@junterpfe , do we know all the required URLs under .microsoft.us that is required?

It feels weird to have .microsoft.us and gov.api.flow.microsoft.us on the same list.

One thing we can do is to have  something like this:

- microsoft.us (flow.microsoft.us, xxx.microsoft.us, yyy.microsoft.us)

This way, customers can decide to blanket allow microsoft.us or decide to go more specific into all the required URLs within .microsoft.us

**Comment by junterpfe** [comment]
I would love to have a full list of what is required, that's exactly what IRS wants. But sadly I have yet to find such a list.

John Unterseher MCSE MCSA MCT
Microsoft CSA
813.260.0162

If you have any feedback about my work, please let me or my manager Chris Sloyan ***@***.******@***.***> know or fill out the following form Feedback<http://aka.ms/junterfeedback>

**Comment by pdib** [comment]
@junterpfe As a starting point for your work with the customer, you can take all endpoints that end with `.microsoft.com` [here](https://learn.microsoft.com/en-us/power-automate/ip-address-configuration) and replace with `.microsoft.us`. If you're able to validate this with the customer, I'm fine with adding it to the doc page here, but please use the format @kenseongtan proposed - it makes it a little clearer that these are the required subdomains)

**Comment by junterpfe** [comment]
Would it be easier to add gov.api.flow.microsoft.us to the article you just linked?

John Unterseher MCSE MCSA MCT
Microsoft CSA
813.260.0162

If you have any feedback about my work, please let me or my manager Chris Sloyan ***@***.******@***.***> know or fill out the following form Feedback<http://aka.ms/junterfeedback>

**Comment by pdib** [comment]
Yes, would make sense as well.

**Comment by junterpfe** [comment]
I have requested the change to the doc you pointed out instead, you can probably discard this pull

John Unterseher MCSE MCSA MCT
Microsoft CSA
813.260.0162

If you have any feedback about my work, please let me or my manager Chris Sloyan ***@***.******@***.***> know or fill out the following form Feedback<http://aka.ms/junterfeedback>

**Pull request closed without merging**
