### PR TITLE
Adding High density

### PR DESCRIPTION
**Pull request by gachasta**
Run multiple concurrent UI flows on Windows Server devices.

Deon can you check that the links work on your end? I'm unsure about the relative link to the other section in the content that I added.

Thx!

### CODE REVIEW

**Comment by PRMerger17** [comment]
@gachasta : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by raaourik** [comment]
@MSFTMan could you please merge this PR today. The new version has been released today and is now available to the public.
Thanks

**Comment by PRMerger6** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger8** [comment]
@gachasta : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger6** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Pull request merged**
