### PR TITLE
Add DLP for RPA session

### PR DESCRIPTION
**Pull request by lanlanlee2008**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@lanlanlee2008 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger5** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by MSFTMan — APPROVED** [review]

**Comment by PRMerger8** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
