### PR TITLE
Korean Translation for Setup.md

### PR DESCRIPTION
**Pull request by lawbot4me**
Hi,

I'm an RPA trainer of Automation Anywhere.
RPA is my favorite interest and I'm using Power Automate to automate my legal tech service to create a simple contract online.
Recently, I'm studying Power Automate Desktop(preview) in a group, called _"I love hands-on"_.
I've just translated the setup.md in Korean for Korean learners.
To avoid complexity, I've renamed the file name with 'setup-kr.md'.
Hope this will help Korean Learners.

Gratefully yours,
Inhee

### CODE REVIEW

**Comment by PRMerger18** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger7** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger7** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger12** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger15** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger8** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger9** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger9** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger8** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger13** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger13** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger19** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol

**Comment by PRMerger20** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol

**Comment by PRMerger6** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol

**Comment by PRMerger10** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol

**Comment by PRMerger12** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol

**Comment by PRMerger20** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol

**Comment by PRMerger7** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol

**Comment by PRMerger18** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol

**Comment by PRMerger20** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol

**Comment by PRMerger13** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol

**Comment by PRMerger18** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol

**Comment by PRMerger18** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol

**Comment by PRMerger17** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol, @olegmelnykov

**Comment by PRMerger17** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol, @olegmelnykov

**Comment by PRMerger20** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @olegmelnykov, @rokontol

**Comment by PRMerger20** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @olegmelnykov, @rokontol

**Comment by PRMerger15** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @olegmelnykov, @rokontol

**Comment by PRMerger17** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @olegmelnykov, @rokontol

**Comment by PRMerger18** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @olegmelnykov, @rokontol

**Comment by PRMerger18** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @olegmelnykov, @rokontol

**Comment by PRMerger18** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @olegmelnykov, @rokontol

**Comment by PRMerger9** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @olegmelnykov, @rokontol

**Comment by PRMerger10** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol, @olegmelnykov

**Comment by PRMerger12** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol, @olegmelnykov

**Comment by PRMerger17** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol, @olegmelnykov, @mariosleon

**Comment by PRMerger20** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @rokontol, @olegmelnykov, @mariosleon

**Comment by PRMerger8** [comment]
@lawbot4me : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman, @olegmelnykov, @rokontol, @mariosleon

**Comment by PRMerger9** [comment]
@BestTechSystem : Thanks for your contribution! The author(s) have been notified to review your proposed change. @olegmelnykov, @msftman, @rokontol, @mariosleon

**Comment by MSFTMan** [comment]
@lawbot4me Thank you for working on these. We've discussed internally, and unfortunately, we aren't able to use these translations. Thank you again for using Power Automate.

**Pull request closed without merging**
