### PR TITLE
Update limits-and-config.md

### PR DESCRIPTION
**Pull request by ChrisGarty**
In response discussion with CSS and @PriyaKodukula this morning...
Remove reference to exporting a flow to see its plan
Add limits column for entitlement vs interim
Help users figure out what their current plan is

### CODE REVIEW

**Comment by PRMerger14** [comment]
@ChrisGarty : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by ChrisGarty** [comment]
@PriyaKodukula, I converted this to a draft to wait for your review

**Comment by PRMerger6** [comment]
@KumarVivek : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger10** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger20** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger15** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger16** [comment]
@KumarVivek : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger18** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Review by MSFTMan — APPROVED** [review]

**Comment by PRMerger6** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Pull request merged**
