### PR TITLE
Update limits-and-config.md

### PR DESCRIPTION
**Pull request by PriyaKodukula**
Removed entitlement limits and only pointed to doc with revised limits

### CODE REVIEW

**Comment by PRMerger15** [comment]
@PriyaKodukula : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@PriyaKodukula : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by PriyaKodukula — COMMENTED** [review]
Added clarity about transition period

**Comment by PRMerger9** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by MSFTMan — APPROVED** [review]

**Comment by PRMerger19** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
