### PR TITLE
Update limits-and-config.md

### PR DESCRIPTION
**Pull request by ChrisGarty**
Added the language of "expiration" and "expire"

### CODE REVIEW

**Comment by PRMerger14** [comment]
@ChrisGarty : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger15** [comment]
@ChrisGarty : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger7** [comment]
@ChrisGarty : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger8** [comment]
@ChrisGarty : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Review by MSFTMan — APPROVED** [review]

**Comment by PRMerger9** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Pull request merged**
