### PR TITLE
add a line in to help users find the machine runtime

### PR DESCRIPTION
**Pull request by simone-bennett**
I was trying to set this up and took a little bit to find the machine runtime setup/installer. Added a line to show people where that is.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@simone-bennett : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger5** [comment]
@KumarVivek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by georgiostrantzas — CHANGES_REQUESTED** [review]
@simone-bennett @KumarVivek @mariosleon In the documentation, we use the term "Power Automate for desktop" instead of "Power Automate Desktop". Also, it's preferable to use the same letter casing as the UI, so change the "Open Machine Settings" section to "Open machine settings".

**Comment by PRMerger15** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@georgiostrantzas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@georgiostrantzas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by georgiostrantzas — APPROVED** [review]

**Pull request merged**
