### PR TITLE
Update us-govt gateway information.md

### PR DESCRIPTION
**Pull request by thomasjeffries11**
Related to this PR for Power Apps: https://github.com/MicrosoftDocs/power-platform/pull/747

Article references a gateway whitelisting process and advises customers to open a support case to have it done. As far as I am aware (I'm in support) this is no longer necessary.

I am proposing a change to the gateway section to reflect this. Alternatively, you could argue that the entire gateway section could be deleted as there really is no difference in this functionality between commercial and US Gov customers.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@thomasjeffries11 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger9** [comment]
@thomasjeffries11 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger15** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Review by MSFTMan — APPROVED** [review]

**Comment by PRMerger8** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger14** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Pull request merged**
