### PR TITLE
Update create-team-flows.md

### PR DESCRIPTION
**Pull request by jstrong013**
Fix minor spelling mistake.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@jstrong013 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by menum724** [comment]
Where does Microsoft Azure Pipeline fit.

**Comment by PRMerger13** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by MSFTMan** [comment]
@jstrong013  Thanks for making a contribution to the Power Automate docs!

**Pull request merged**
