### PR TITLE
Update process-advisor-security.md

### PR DESCRIPTION
**Pull request by alanabrito**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@alanabrito : Thanks for your contribution! The author(s) have been notified to review your proposed change. @nijemcevic

**Comment by PRMerger20** [comment]
@alanabrito : Thanks for your contribution! The author(s) have been notified to review your proposed change. @nijemcevic

**Comment by PRMerger13** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @nijemcevic

**Review by MSFTMan — APPROVED** [review]

**Comment by PRMerger8** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @nijemcevic

**Pull request merged**
