### PR TITLE
Update connection-cds-native.md

### PR DESCRIPTION
**Pull request by davidyack**
removed line saying solution aware flow is required

### CODE REVIEW

**Comment by KumarVivek** [comment]
@MSFTMan @JimDaly Can you pls validate this change?

**Comment by JimDaly** [comment]
Adding @prsi-msft  since he owns these docs. But it looks good to me.

**Comment by prsi-msft** [comment]
@JimDaly @davidyack 
A better change would have been to retain the line, and say that both solution-aware and solution-agnostic flows can be created using CDS current environment. Can you please modify?

**Comment by PRMerger8** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @MSFTMAN

**Pull request merged**
