### PR TITLE
Fixes issue #200

### PR DESCRIPTION
**Pull request by GiantCrocodile**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@GiantCrocodile : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by MSFTMan** [comment]
@GiantCrocodile Thanks for your submission. Why do you think this needs to be changed? Thanks!

**Comment by GiantCrocodile** [comment]
@MSFTMan I think this is quite obvious: The pricing page doesn't show you which subscription/plan you have. It shows you which you can buy but that is regardless of which you have.

**Comment by PRMerger12** [comment]
@GiantCrocodile : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger12** [comment]
@KumarVivek : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Pull request merged**
