### PR TITLE
Update limits-and-config.md

### PR DESCRIPTION
**Pull request by PriyaKodukula**
Updated the Runs to actions and added Interim limits

### CODE REVIEW

**Comment by PRMerger17** [comment]
@PriyaKodukula : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger15** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Review by MSFTMan — APPROVED** [review]
Thanks for your contribution, Priya. I renamed "entitilement" to "plan limit"

**Comment by PRMerger16** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Pull request merged**
