### PR TITLE
Adding storage limits for Power Automate

### PR DESCRIPTION
**Pull request by rajsesh**
The storage limits for power automate plans.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoftdocs/power-automate-docs/320)

### CODE REVIEW

**Comment by PRMerger15** [comment]
@rajsesh : Thanks for your contribution! The author(s) have been notified to review your proposed change. @stepsic-microsoft-com

**Comment by PRMerger18** [comment]
@rajsesh : Thanks for your contribution! The author(s) have been notified to review your proposed change. @stepsic-microsoft-com

**Comment by PRMerger16** [comment]
@rajsesh : Thanks for your contribution! The author(s) have been notified to review your proposed change. @stepsic-microsoft-com

**Review by MSFTMan — APPROVED** [review]

**Comment by PRMerger7** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @stepsic-microsoft-com

**Pull request merged**
