### PR TITLE
Update learning-catalog-app-maker.md

### PR DESCRIPTION
**Pull request by amsilb**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@amsilb : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger13** [comment]
@amsilb : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger9** [comment]
@amsilb : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger9** [comment]
@amsilb : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by amsilb** [comment]
@DaveBeasley

**Comment by DaveBeasley** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@DaveBeasley: I'm sorry - only the author of this article, @msftman, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by DaveBeasley** [comment]
@msftman -- this updates the learning catalog with Process Advisor. Can you merge?

**Comment by PRMerger12** [comment]
@amsilb : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger18** [comment]
@amsilb : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger10** [comment]
@amsilb : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger16** [comment]
@amsilb : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger10** [comment]
@amsilb : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by DaveBeasley** [comment]
@MSFTMan -- ready for merge based on your feedback.

**Comment by PRMerger10** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Pull request merged**
