### PR TITLE
Update limits-and-config.md

### PR DESCRIPTION
**Pull request by llistephanie**
Updating concurrency behavior.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@llistephanie : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@llistephanie : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by rajsesh — APPROVED** [review]

**Review by mihshahmsft — APPROVED** [review]

**Comment by PRMerger3** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by MSFTMan — APPROVED** [review]

**Comment by PRMerger14** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
