### PR TITLE
Update daily limits to current values

### PR DESCRIPTION
**Pull request by masisley**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@masisley : Thanks for your contribution! The author(s) have been notified to review your proposed change. @stepsic-microsoft-com

**Comment by PRMerger12** [comment]
@masisley : Thanks for your contribution! The author(s) have been notified to review your proposed change. @stepsic-microsoft-com

**Comment by PRMerger14** [comment]
@masisley : Thanks for your contribution! The author(s) have been notified to review your proposed change. @stepsic-microsoft-com

**Review by MSFTMan — APPROVED** [review]

**Comment by PRMerger12** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger13** [comment]
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Pull request merged**
